### ISSUE TITLE
phip merge-columns -m good substitution?

### ISSUE THREAD

**Issue by yimei-li** [matsengrp/phippery#136]
Hey sorry to bother you again, I come from https://github.com/lasersonlab/phip-stat/issues/21

Could you please tell me which part/commend in **phippery** can be a good replacement for `phip merge-columns -m outer -i sample_counts -o counts.tsv`? I have trouble using "-m" in the command `phip merge-columns -m outer`

**Comment by jgallowa07** [comment]
Hi @yimei-li ! Sorry we're currently in a push to complete things - and should have a stable version w/ more complete documentation coming out early in January. Things a currently quite in flux, and we usually expect the counts are merged using out nextflow pipeline (also currently in flux) 

However, we merge our tsv's using the following [source code](https://github.com/matsengrp/phippery/blob/110a2db35197a41b3de674c81c05c2a5e1d50cbe/phippery/phipdata.py#L100)you might find useful for the time being.
This function assumes that you have tsv's named "<sample_id>.tsv" where sample id is a unique identifier. So if you have a directory of tsv's containing your counts like 0.counts, 1.counts ... and each is formatted like:
```
(base) ubuntu sim-example-output/counts ‹main*› » head -n 5 0.counts 
0	1
1	1
2	1
3	1
4	1
```
where the first column is a unique peptide ID and the second is te number of alignments reported for that peptide, then you can merge then like this, using the `phippery` API:
```
>>> import phippery
>>> from phippery.phipdata import *
>>> import glob
>>> files = glob.glob("*.counts")
>>> collect_merge_prune_counts(files)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'collect_merge_prune_counts' is not defined
>>> collect_merge_prune_count_data(files)
           0   1   2   3   4   5   6   7   8   9   10  11
sample_id
0           1   1   1   1   1   1   1   1   1   1   1   1
1           1   1   1   1   1   1   1   1   1   1   1   1
2           1   1   1   1   1   1   1   1   1   1   1   1
3           1   1   1   1   1   1   1   1   1   1   1   1
4           1   1   1   1   1   1   1   1   1   1   1   1
5           1   1   1   1   1   1   1   1   1   1   1   1
6           1   1   1   1   1   1   1   1   1   1   1   1
7           1   1   1   1   1   1   1   1   1   1   1   1
8           1   1   1   1   1   1   1   1   1   1   1   1
9           1   1   1   1   1   1   1   1   1   1   1   1
```
feel free to use this either by loading the API, or copying the source code directly into you own script.
Does this answer your question? Again, once things get cleaned up we will recommend using the [Nextflow pipeline ](https://github.com/matsengrp/phip-flow)and it's associated sub workflows for processing counts, and performing various beneficial analysis. Sorry for the delay!
