### ISSUE TITLE
Document virscan agg optional workflow

### ISSUE THREAD

**Issue by jgallowa07** [matsengrp/phippery#155]
Sam added the very nice [Aggregation / Public epitopes workflow](https://github.com/matsengrp/phip-flow/blob/main/workflows/aggregate.nf), The usage should be documented with a small overview / blurb -> [here](https://github.com/matsengrp/phippery/blob/main/docs/alignments-pipeline.rst#virscan-public-epitopes)

@sminot would you mind giving this a go when you're available? Thanks!

**Comment by sminot** [comment]
Will do!

**Comment by jgallowa07** [comment]
@sminot We're submitting the manuscript this week (possibly today). (Not to be pushy, I don't think it's critical by any means) Do you know when you might have time to address this?

**Comment by sminot** [comment]
Thank you for the nudge! Please let me know what you think of the content in the PR
