### ISSUE TITLE
Double-ended sequencing data

### ISSUE THREAD

**Issue by liangjiameng** [matsengrp/phippery#183]
Excuse me！
My library sequencing uses double-ended sequencing, how do I add **R1.fastq** and **R.fastq** to the sample_table.csv file

**Comment by jgallowa07** [comment]
Hi @liangjiameng Sorry for the late reply. 

We do not currently support paored-end sequencing.  See the [updated documentation](https://matsengrp.github.io/phippery/examples.html#alignment-approach) outlining our alignment approach.

That said, the pipeline modifications to do so would be quite strait-forward for anyone familiar with Nextflow. I would gladly oversee a PR if this is something you, or anyone else would like to contribute. I'll close the issue for now, but if you would like to contribute this feature feel free to re-open this for any questions, or simply submit the PR.
